In [2]:
import numpy as np
import pandas as pd
from sklearn import model_selection

In [10]:
data = np.genfromtxt("xyTrain.csv",delimiter=",")
data.shape

(379, 14)

In [13]:
x = data[:,0:13]
y = data[:,13]

(379,)

In [14]:
df = pd.DataFrame(x)

In [15]:
df["new"] = 1

In [16]:
x = df.values

In [33]:
xTrain,xTest,yTrain,yTest = model_selection.train_test_split(x,y,random_state=0)

In [34]:
def step(x,y,learnRate,m):
    N = len(x)
    M = len(m)
    for i in range(M):
        slope_m = 0
        for j in range(N):
            slope_m +=(-2/N)*(y[j]-(m*x[j]).sum())*x[j][i]
        m[i] = m[i]-(learnRate*slope_m)
    return m

In [35]:
def cost(x,y,m):
    N = len(x)
    ct = 0
    for i in range(N):
        ct+=(1/N)*((y[i]-((m*x[i]).sum()))**2)
    return ct

In [36]:
def gd(x,y,numIter,learnRate):
    m = np.zeros(x.shape[1])
    ct = cost(x,y,m)
    for i in range(numIter):
        m  = step(x,y,learnRate,m)
        cNew = cost(x,y,m)
        print(cNew)
    return m

In [40]:
def run(x,y):
    numIter = 150
    learnRate = 0.2
    m = gd(x,y,numIter,learnRate)
    dfm = pd.DataFrame(m)
    return m

In [42]:
def fit(x,y):
    m = run(xTrain,yTrain)
    return m

In [44]:
def pre(x,m):
    N = len(x)
    yPre = np.zeros(N)
    for i in range(N):
        yPre[i] = (x[i]*m).sum()
    return yPre

In [46]:
m = fit(xTrain,yTrain)
yPre = pre(xTest,m)

218.044214763
94.9201896967
51.4077171795
35.3208585102
28.9996686375
26.2928525626
24.9917049485
24.2775572313
23.833923949
23.5306122437
23.3091389586
23.1402201503
23.0074658523
22.9007920026
22.8135474395
22.7411325079
22.680261779
22.628532452
22.5841534714
22.5457672902
22.512328911
22.4830220633
22.4572002055
22.4343444583
22.414033251
22.3959201634
22.3797175607
22.3651843629
22.3521167952
22.3403413082
22.3297090964
22.3200918037
22.3113781227
22.303471072
22.2962857959
22.2897477675
22.2837913107
22.2783583728
22.2733974984
22.2688629657
22.2647140547
22.2609144239
22.2574315766
22.2542364016
22.2513027765
22.2486072233
22.2461286095
22.243847886
22.2417478588
22.2398129878
22.2380292098
22.2363837833
22.2348651501
22.2334628138
22.2321672318
22.2309697192
22.2298623637
22.2288379491
22.2278898883
22.2270121622
22.2261992661
22.2254461607
22.2247482292
22.2241012384
22.2235013034
22.2229448563
22.2224286179
22.2219495724
22.2215049438
22.2210921758
22.2207089125
22.2203529816
22.2200223787
22.2197152536
22.2194298976
22.2191647314
22.2189182952
22.2186892389
22.2184763131
22.2182783614
22.2180943129
22.2179231758
22.217764031
22.2176160264
22.2174783723
22.2173503361
22.2172312383
22.2171204483
22.217017381
22.216921493
22.2168322802
22.2167492741
22.2166720397
22.2166001729
22.2165332983
22.216471067
22.2164131549
22.2163592606
22.2163091039
22.2162624246
22.2162189805
22.2161785465
22.2161409133
22.2161058862
22.2160732842
22.2160429389
22.2160146935
22.2159884025
22.2159639303
22.2159411508
22.2159199466
22.2159002086
22.2158818352
22.2158647319
22.2158488108
22.2158339901
22.2158201935
22.2158073503
22.2157953944
22.2157842645
22.2157739035
22.2157642581
22.215755279
22.21574692
22.2157391384
22.2157318941
22.21572515
22.2157188717
22.2157130268
22.2157075855
22.2157025199
22.215697804
22.2156934137
22.2156893265
22.2156855214
22.215681979
22.2156786811
22.2156756108
22.2156727525
22.2156700915
22.2156676141
22.2156653077
22.2156631605
22.2156611615
22.2156593005
22.2156575679
22.2156559549
22.2156544532
22.2156530552
22.2156517536

In [49]:
dfy = pd.DataFrame(yPre)
dfy

            0
0   24.482596
1   19.842906
2   24.530829
3   23.309390
4   18.122594
5    7.716003
6   20.057350
7   25.321243
8   18.924283
9   19.278131
10  25.544300
11  16.831551
12  42.329255
13  34.918041
14  21.246683
15  30.760800
16  20.464104
17  33.143581
18  25.015268
19   7.589271
20  18.396399
21  26.733831
22  18.878264
23  40.190199
24  26.523022
25  16.093335
26  16.498913
27  21.962171
28  13.370520
29  34.538123
..        ...
65  28.750899
66   2.883318
67  17.041033
68  12.679469
69  18.050515
70  36.552556
71  13.821813
72  13.481950
73  30.383326
74  16.654694
75  24.831537
76  20.563121
77  31.135620
78  22.898852
79  15.766510
80  21.066463
81  32.624273
82  18.665516
83  14.022851
84  15.341749
85  24.913379
86  27.420107
87  20.820389
88  17.784045
89  13.162744
90  25.474122
91  30.953865
92  13.503041
93  15.009287
94  13.353153

[95 rows x 1 columns]

In [51]:
dfyt = pd.DataFrame(yTest)
dfyt

       0
0   23.8
1   19.9
2   20.1
3   20.4
4   20.0
5    5.0
6   20.1
7   24.8
8   14.1
9   16.7
10  18.5
11  13.9
12  50.0
13  43.8
14  16.2
15  30.8
16  18.8
17  31.6
18  29.6
19   7.2
20  20.8
21  23.7
22  16.6
23  50.0
24  23.2
25  20.6
26  15.0
27  20.9
28   9.5
29  34.9
..   ...
65  22.9
66  17.9
67  19.5
68  12.3
69  17.4
70  36.5
71  13.5
72  14.3
73  30.1
74  20.2
75  24.6
76  20.5
77  32.2
78  20.0
79  11.7
80  21.8
81  28.2
82  14.5
83  11.5
84  19.0
85  22.8
86  24.5
87  15.3
88  19.9
89  15.6
90  50.0
91  34.7
92   7.5
93  14.8
94  13.4

[95 rows x 1 columns]

In [68]:
N = len(yPre)
for i in range(N):
    yPre[i] = float("{0:.1f}".format(yPre[i]))

In [70]:
np.savetxt("yPre.csv",yPre,'%5.1f')